name: Upload component

on:
  push:
    tags:
      - "v*"

jobs:
  upload_components:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Upload component to ESP Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "wsm_driver: ."
          namespace: "wiznet"